image:
  repository: ghcr.io/huggingface
  name: chat-ui
  tag: 0.0.0-latest
  pullPolicy: IfNotPresent

replicas: 3

domain: chat-ui.hub-alb.huggingface.tech

service:
  type: NodePort
  annotations: { }

ingress:
  annotations: { }

resources:
  requests:
    cpu: 1
    memory: 8Gi
  limits:
    cpu: 1
    memory: 8Gi
nodeSelector: {}
tolerations: []

envVars: { }
externalSecrets:
  enabled: false
  secretStoreName: ""
  secretName: ""
  parameters: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: ""
  targetCPUUtilizationPercentage: ""

monitoring:
  enabled: false
