services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  model:
    image: ghcr.io/ggerganov/llama.cpp:full-cuda
    environment:
      - WEIGHTS_FILENAME=${WEIGHTS_FILENAME}
      - NGL=${NGL}
      - CONTEXT_LENGTH=${CONTEXT_LENGTH}
    command: --server -m /models/${WEIGHTS_FILENAME} -c ${CONTEXT_LENGTH} -ngl ${NGL} --port 80 --host 0.0.0.0
    ports: 
      - 8080:80
    volumes:
      - ./data:/models
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]

  chat:
    image: node:19
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MODEL_ID=${MODEL_ID}
    working_dir: /app
    ports:
      - 5173:5173
    volumes:
      - ./:/app
    depends_on:
      - mongo
      - model