nodeSelector:
  role-hub-utils: "true"

tolerations:
  - key: CriticalAddonsOnly
    operator: Equal
    
ingress:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "chat-ui.hub-alb.huggingface.tech"
    alb.ingress.kubernetes.io/healthcheck-path: "/healthcheck"
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80}, {\"HTTPS\": 443}]"
    alb.ingress.kubernetes.io/group.name: "hub-prod"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/tags: "Env=prod,Project=hub,Terraform=true"
    alb.ingress.kubernetes.io/target-node-labels: "role-hub-utils=true"
    kubernetes.io/ingress.class: "alb"

envVars:
  ALTERNATIVE_REDIRECT_URLS: '["huggingchat://login/callback"]'
  APP_BASE: "/chat"
  ENABLE_ASSISTANTS: "true"
  ENABLE_ASSISTANTS_RAG: "true"
  EXPOSE_API: "true"
  MESSAGES_BEFORE_LOGIN: 0
  MODELS: > 
    [
      {
        "name": "CohereForAI/c4ai-command-r-plus",
        "tokenizer": "Xenova/c4ai-command-r-v01-tokenizer",
        "description": "Command R+ is Cohere's latest LLM and is the first open weight model to beat GPT4 in the Chatbot Arena!",
        "modelUrl": "https://huggingface.co/CohereForAI/c4ai-command-r-plus",
        "websiteUrl": "https://docs.cohere.com/docs/command-r-plus",
        "logoUrl": "https://huggingface.co/datasets/huggingchat/models-logo/resolve/main/cohere-logo.png",
        "parameters": {
          "stop": [ "<|END_OF_TURN_TOKEN|>" ],
          "truncate": 28672,
          "max_new_tokens": 4096,
          "temperature": 0.3
        },
        "promptExamples": [
          {
            "title": "Write an email from bullet list",
            "prompt": "As a restaurant owner, write a professional email to the supplier to get these products every week: 
                                                   
                       - Wine (x10)
                       - Eggs (x24)
                       - Bread (x12)"
          }, {
            "title": "Code a snake game",
            "prompt": "Code a basic snake game in python, give explanations for each step."
          }, {
            "title": "Assist in a task",
            "prompt": "How do I make a delicious lemon cheesecake?"
          }
        ]
      },
    ]
  OLD_MODELS: >
    [
      { "name": "bigcode/starcoder" },
      { "name": "OpenAssistant/oasst-sft-6-llama-30b-xor" },
      { "name": "HuggingFaceH4/zephyr-7b-alpha" },
      { "name": "openchat/openchat_3.5" },
      { "name": "openchat/openchat-3.5-1210" },
      { "name": "tiiuae/falcon-180B-chat" },
      { "name": "codellama/CodeLlama-34b-Instruct-hf" },
      { "name": "google/gemma-7b-it" },
      { "name": "meta-llama/Llama-2-70b-chat-hf" },
      { "name": "codellama/CodeLlama-70b-Instruct-hf" },
      { "name": "openchat/openchat-3.5-0106" }
    ]
  PUBLIC_ORIGIN: "https://huggingface.co"
  PUBLIC_SHARE_PREFIX: "https://hf.co/chat"
  PUBLIC_ANNOUNCEMENT_BANNERS: "[]"
  PUBLIC_APP_NAME: "HuggingChat"
  PUBLIC_APP_ASSETS: "huggingchat"
  PUBLIC_APP_COLOR: "yellow"
  PUBLIC_APP_DESCRIPTION: "Making the community's best AI chat models available to everyone."
  PUBLIC_APP_DISCLAIMER_MESSAGE: "Disclaimer: AI is an area of active research with known problems such as biased generation and misinformation. Do not use this application for high-stakes decisions or advice."
  PUBLIC_APP_DATA_SHARING: 0
  PUBLIC_APP_DISCLAIMER: 1
  PUBLIC_PLAUSIBLE_SCRIPT_URL: "/js/script.js"
  PUBLIC_APPLE_APP_ID: "6476778843"
  REQUIRE_FEATURED_ASSISTANTS: "true"
  TASK_MODEL: "meta-llama/Meta-Llama-3-8B-Instruct"
  TEXT_EMBEDDING_MODELS: >
    [{
      "name": "bge-base-en-v1-5-sxa",
      "displayName": "bge-base-en-v1-5-sxa",
      "chunkCharLength": 512,
      "endpoints": [{ 
        "type": "tei",
        "url": "https://huggingchat-tei.hf.space/"
      }]
    }]
  WEBSEARCH_BLOCKLIST: '["youtube.com", "twitter.com"]'

externalSecrets:
  enabled: true
  secretStoreName: "chat-ui-prod-secretstore"
  secretName: "chat-ui-prod-secrets"
  parameters:
    MONGODB_URL: "hub-prod-chat-ui-mongodb-url"
    OPENID_CONFIG: "hub-prod-chat-ui-openid-config"
    SERPER_API_KEY: "hub-prod-chat-ui-serper-api-key"
    HF_TOKEN: "hub-prod-chat-ui-hf-token"
    WEBHOOK_URL_REPORT_ASSISTANT: "hub-prod-chat-ui-webhook-report-assistant"
    ADMIN_API_SECRET: "hub-prod-chat-ui-admin-api-secret"
    USAGE_LIMITS: "hub-prod-chat-ui-usage-limits"
