name: Lint and test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: |
          npm install ci
      - name: "Checking lint/format errors"
        run: |
          npm run lint
      - name: "Checking type errors"
        run: |
          npm run check
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: |
          npm ci
      - name: "Tests"
        run: |
          # Docker compose does not support some of the syntax we use in the .env and there is no option to disable automatic loading. See: https://github.com/docker/compose/issues/6741
          mv .env _.env
          docker-compose up -d 
          mv _.env .env
          npm run test
